version: '3.8'

services:
  registry:
    image: clytze/piggy-registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    image: clytze/piggy-auth-grpc
    restart: always
    depends_on:
      - auth-mongodb
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    image: clytze/piggy-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    image: clytze/piggy-account-grpc
    restart: always
    depends_on:
      - account-mongodb
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    image: clytze/piggy-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-service:
    image: clytze/piggy-statistics-grpc
    restart: always
    depends_on:
      - statistics-mongodb
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-mongodb:
    image: clytze/piggy-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    image: clytze/piggy-notification-grpc
    restart: always
    depends_on:
      - notification-mongodb
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-mongodb:
    image: clytze/piggy-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
