version: '3.7'

services:
  registry:
    image: clytze/piggy-registry
    restart: always
    ports:
      - "8761:8761"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - eureka-network

  auth-service-grpc:
    image: clytze/piggy-auth-grpc
    restart: always
    ports:
      - "9091:9091"
    depends_on:
      - auth-mongodb
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb://user:password@auth-mongodb:27017/auth-service?authSource=admin
      SPRING_DATA_MONGODB_USERNAME: user
      SPRING_DATA_MONGODB_PASSWORD: password
    networks:
      - eureka-network

  auth-mongodb:
    image: clytze/piggy-mongodb
    restart: always
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    tmpfs:
      - /data/db
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - eureka-network

  account-service-grpc:
    image: clytze/piggy-account-grpc
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - account-mongodb
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb://user:password@account-mongodb:27017/account-service?authSource=admin
      SPRING_DATA_MONGODB_USERNAME: user
      SPRING_DATA_MONGODB_PASSWORD: password
    networks:
      - eureka-network

  account-mongodb:
    image: clytze/piggy-mongodb
    restart: always
    ports:
      - "27018:27017"
    command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    tmpfs:
      - /data/db
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - eureka-network

  statistics-service-grpc:
    image: clytze/piggy-statistics-grpc
    restart: always
    ports:
      - "9093:9093"
    depends_on:
      - statistics-mongodb
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb://user:password@statistics-mongodb:27017/statistics-service?authSource=admin?authSource=admin
      SPRING_DATA_MONGODB_USERNAME: user
      SPRING_DATA_MONGODB_PASSWORD: password
    networks:
      - eureka-network

  statistics-mongodb:
    image: clytze/piggy-mongodb
    restart: always
    ports:
      - "27019:27017"
    command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    tmpfs:
      - /data/db
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - eureka-network

  notification-service-grpc:
    image: clytze/piggy-notification-grpc
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - notification-mongodb
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb://user:password@notification-mongodb:27017/notification-service?authSource=admin
      SPRING_DATA_MONGODB_USERNAME: user
      SPRING_DATA_MONGODB_PASSWORD: password
    networks:
      - eureka-network

  notification-mongodb:
    image: clytze/piggy-mongodb
    restart: always
    ports:
      - "27020:27017"
    command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    tmpfs:
      - /data/db
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge
