# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"R\n\x14NotificationSettings\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12*\n\tfrequency\x18\x02 \x01(\x0e\x32\x17.notification.Frequency\"w\n\x11NotificationEntry\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.notification.NotificationType\x12\x34\n\x08settings\x18\x02 \x01(\x0b\x32\".notification.NotificationSettings\"p\n\tRecipient\x12\x13\n\x0b\x61\x63\x63ountName\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12?\n\x16scheduledNotifications\x18\x03 \x03(\x0b\x32\x1f.notification.NotificationEntry\"#\n\x13GetRecipientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"R\n\x16UpdateRecipientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\trecipient\x18\x02 \x01(\x0b\x32\x17.notification.Recipient\"?\n\x11RecipientResponse\x12*\n\trecipient\x18\x01 \x01(\x0b\x32\x17.notification.Recipient**\n\tFrequency\x12\x07\n\x03LOW\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x08\n\x04HIGH\x10\x02**\n\x10NotificationType\x12\n\n\x06\x42\x41\x43KUP\x10\x00\x12\n\n\x06REMIND\x10\x01\x32\xc3\x01\n\x13NotificationService\x12R\n\x0cGetRecipient\x12!.notification.GetRecipientRequest\x1a\x1f.notification.RecipientResponse\x12X\n\x0fUpdateRecipient\x12$.notification.UpdateRecipientRequest\x1a\x1f.notification.RecipientResponseB?\n(com.piggy.microservice.notification.grpcB\x11NotificationProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.piggy.microservice.notification.grpcB\021NotificationProtoP\000'
  _globals['_FREQUENCY']._serialized_start=541
  _globals['_FREQUENCY']._serialized_end=583
  _globals['_NOTIFICATIONTYPE']._serialized_start=585
  _globals['_NOTIFICATIONTYPE']._serialized_end=627
  _globals['_NOTIFICATIONSETTINGS']._serialized_start=36
  _globals['_NOTIFICATIONSETTINGS']._serialized_end=118
  _globals['_NOTIFICATIONENTRY']._serialized_start=120
  _globals['_NOTIFICATIONENTRY']._serialized_end=239
  _globals['_RECIPIENT']._serialized_start=241
  _globals['_RECIPIENT']._serialized_end=353
  _globals['_GETRECIPIENTREQUEST']._serialized_start=355
  _globals['_GETRECIPIENTREQUEST']._serialized_end=390
  _globals['_UPDATERECIPIENTREQUEST']._serialized_start=392
  _globals['_UPDATERECIPIENTREQUEST']._serialized_end=474
  _globals['_RECIPIENTRESPONSE']._serialized_start=476
  _globals['_RECIPIENTRESPONSE']._serialized_end=539
  _globals['_NOTIFICATIONSERVICE']._serialized_start=630
  _globals['_NOTIFICATIONSERVICE']._serialized_end=825
# @@protoc_insertion_point(module_scope)
